project:
  type: website

website:
  title: "Tom Fletcher"
  navbar:
    right:
      - about.qmd
      - journal.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - flatly
    css: styles.css



